version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: "daily"
    timezone: "America/Denver"
  assignees:
    - "Dragonlord1005"
  
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    timezone: "America/Denver"
    
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: "daily"
    timezone: "America/Denver"
  target-branch: "Inventory"
  assignees:
    - "Dragonlord1005"
