version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    timezone: "America/Denver"
  
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    timezone: "America/Denver"
