version = 1

test_patterns = [
    "tests/**",
    "test.py",
    ".style.py",
    "typey.py"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  skip_doc_coverage = ["module", "init", "class"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[transformers]]
name = "autopep8"
enabled = false
