version = 1

test_patterns = [
    "tests/**",
    "test.py",
    ".style.py",
]

[[analyzers]]
name = "python"
enabled = true
skip_doc_coverage = ["module", "init", "class"]

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "autopep8"
enabled = false
