version = 1

test_patterns = [
    "examples/**",
    "test,py",
    ".style.py",
    "examples/pygame.py"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.8.9"

[[transformers]]
name = "autopep8"
enabled = false