version = 1

test_patterns = [
    "tests/**",
    "gametest.py",
    ".style.py",
    "typey.py",
    "playground.py"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  skip_doc_coverage = ["module", "init", "class"]

