version = 1

test_patterns = [
    "tests/**",
    "gametest.py",
    ".style.py",
    "typey.py",
    "playground.py"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  skip_doc_coverage = ["module", "init", "class"]

[[analyzers]]
name = "test-coverage"
enabled = true
# Install pytest and pytest-cov pacakages from pip
pip install pytest pytest-cov

# Run pytest with --cov and --cov-report flags
pytest --cov=./ --cov-report xml

# Install deepsource CLI
curl https://deepsource.io/cli | sh

# Set DEEPSOURCE_DSN env variable from repository settings page
export DEEPSOURCE_DSN=https://sampledsn@deepsource.io

# From the root directory, run the report coverage command
./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml

[[transformers]]
name = "autopep8"
enabled = false
