print("Hi! Its me, your friend.")
print("this is a pretty simple test")
print("all I have to do is figure out how to give you options")
print("now for whatever dumb reason, atom hates me, so I cant push these changes until I figure this out, so I'll be right back")
print("so I figured this dumb thing out")
print("Now I have to figure out what I want to do with this whole thing")
