[tool.poetry]
name = "bettery-python-testing"
version = "0.1.0"
description = ""
authors = ["repl.it user <replituser@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
replit = "^2.0.0"
pygame-assets = "^0.1"
setuptools = "^53.0.0"
pygradle = "^0.1.dev0"
poetry = "^1.1.4"
pytest = "^6.2.2"
Pillow = "^8.1.0"
pygame = "^2.0.1"
pygame-frame = "^0.0.6"
numpy = "^1.20.1"
nose = "^1.3.7"
virtualenv = "^20.4.2"
pytz = "^2021.1"
django-extensions = "^3.1.1"
inflect = "^5.2.0"
psutil = "^5.8.0"
wincertstore = "^0.2"
configparser = "^5.0.1"
cython = "^0.29.22"
django = "^3.1.7"
cryptography = "^3.4.6"
pudb = "^2020.1"
docutils = "^0.16"
mock = "^4.0.3"
ordereddict = "^1.1"
feedparser = "^6.0.2"
twisted = "^20.3.0"
anything = "^0.2.1"
autobahn = "^21.2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=1.1.4"]
build-backend = "poetry.masonry.api"
