[tool.poetry]
name = "bettery-python-testing"
version = "0.1.0"
description = ""
authors = ["repl.it user <replituser@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
replit = "^2.0.0"
pygame-assets = "^0.1"
setuptools = "^53.0.0"
pygradle = "^0.1.dev0"
poetry = "^1.1.4"
pytest = "^6.2.2"
Pillow = "^8.1.0"
pygame = "^2.0.1"
pygame-frame = "^0.0.6"
numpy = "^1.20.1"
nose = "^1.3.7"
virtualenv = "^20.4.2"
pytz = "^2021.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=1.1.4"]
build-backend = "poetry.masonry.api"
