[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool]
[tool.poetry]
authors = ["Dragonlord1005"]
description = ""
name = "Python-text-based-game-framework"
version = "0.1.0"
[tool.poetry.dependencies]
python = "^3.8"
yapf = "^0.31.0"
pytest-xdist = "^2.2.1"
pytest = {version = "^6.2.3", allow-prereleases = true}
pytest-benchmark = "^3.4.0"
pytest-sugar = "^0.9.4"
[tool.poetry.dev-dependencies]