[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry>=1.0"]

[tool]
[tool.poetry]
authors = ["Dragonlord1005 68302450+Dragonlord1005@users.noreply.github.com"]
description = ""
name = "Python-text-based-game-framework"
version = "0.0.2"
readme = "README.md"
license = "MIT"
[tool.poetry.dependencies]
python = "^3.8"
pyinstaller = "^4.4"
poethepoet = "^0.10.0"
black = "^21.8b0"
[tool.poetry.dev-dependencies]
yapf = "^0.31.0"
howdoi = "^2.0.18"
pytest = "^6.2.4"
coverage = "^5.5"
pytest-cov = "^2.12"
pytest-sugar = "^0.9.4"
pytest-randomly = "^3.8.0"
