[tool.poetry]
name = "bettery-python-testing"
version = "0.1.0"
description = ""
authors = ["repl.it user <replituser@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^6.2.2"
pygame = "^2.0.1"
pygame-gui = "^0.5.7"
pygame-geometry = "^0.1.2"
pygame-widgets = "^0.3.0"
pygame-menu = "^3.5.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
