[tool.poetry]
name = "bettery-python-testing"
version = "0.1.0"
description = ""
authors = ["repl.it user <replituser@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^6.2.2"
pygame = "^2.0.1"
replit = "^2.0.0"
pygame-assets = "^0.1"
wheel = "^0.36.2"
setuptools = "^53.0.0"
pygradle = "^0.1.dev0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
