# This is a basic workflow to help you get started with Actions

name: Builder

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the the-game branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.4.0
      
      - uses: syphar/restore-pip-download-cache@v1

      - name: Set up Python 3.8.9
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8.9
      
      - name: Get the requirements
        run: pip install -r dev-requirements.txt

      # Runs a set of commands using the runners shell
      - name: build the thing
        run: |
          pyinstaller -D game.py -n ${{ matrix.os }}game
 

      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Results
          path: dist/**
