# This is a basic workflow to help you get started with Actions

name: Pytest

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the the-game branch
  push:
    branches:
    paths:
    - '**.py'
  pull_request:
    branches:
    paths:
    - '**.py'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.4
      - uses: syphar/restore-pip-download-cache@v1
      
      - name: Install the requirements.
        run: |
          pip install -r dev-requirements.txt
      # Runs a set of commands using the runners shell
      - name: Run the test
        run: |
          pytest
